INSERT INTO Category (categoryName) 
VALUES 
    ('Light and Fire'),
    ('DIY'),
    ('Weapons - Hunting equipment'),
    ('Torchlight evening'),
    ('Drinks');

INSERT INTO SubCategory(subCategoryName, FK_categoryId)
VALUES 
    ('Matches', 1),
    ('Lighter', 1),
    ('Torch', 1),
    ('Barbecue', 1),
    ('Hammer', 2),
    ('Stick', 2),
    ('Mace', 3),
    ('Lance', 3),
    ('Fronde', 3),
    ('Bow', 3),
    ('Arrows Pack', 3),
    ('Smoke', 4),
    ('Blazing Food', 4),
    ('Wines', 5),
    ('Beers', 5);

INSERT INTO Item(itemName, itemDescription, itemPrice, itemImg, FK_subCategoryId, FK_categoryId)
VALUES  ('1st price', 'the cheapest', 1, 'https://static.teteamodeler.com/media/cache/thumb_400/7eb2299b03d6d00f8b9fcbfaf51d5dd4cde80c32.png,', 1, 1),
		('decorative', 'the most beautiful matches', 2, 'https://cdn1.smkg.fr/images/Image/produits/pipes-2/accessoire%20pipe/allumette-4saisons-1.jpg', 1, 1),
		('super premium', 'an eternal match', 4, 'https://cdn.shopify.com/s/files/1/0193/9623/1268/products/Screenshot_1_d3fa450b-854a-4afd-86a2-09bb972ced46_600x.jpg?v=1604498786', 1, 1),
		('Multifunction', 'can also be used as an earpick', 3, 'https://www.hpa-shop.fr/164-large_default/allumettes-waterproof.jpg', 1, 1),
		('The big daddy', 'Elon Musk would be proud', 10000, 'https://www.lesaviezvous.net/wp-content/uploads/2014/05/lance-flamme.jpg', 2, 1),
		('The green one', 'Magnificent magnifying lighter', 55, 'https://media.lelombrik.net/t/0b335518bab6f129db5d267791164408/p/01.jpg', 2, 1),
		('the classic', 'It is not much, but it is honest work', 18, 'https://axel-com.com/431-medium_default/briquet-bic.jpg', 2, 1),
		('koh-lanta', 'If you feel you are not tribal enough', 570, 'https://cache.cosmopolitan.fr/data/photo/w1000_ci/52/koh-elimnation.jpg', 3, 1),
		('molotov', 'gilet jaune style', 80, 'https://vignette.wikia.nocookie.net/barovia/images/3/30/Molotov_cocktail.png/revision/latest/top-crop/width/360/height/450?cb=20180221161649&path-prefix=fr', 3, 1),
		('Basic', 'Basic torch is very basic', 12, 'https://image.freepik.com/vecteurs-libre/torche-bois-feu-brulant-flamme-brillante-etincelles_99660-238.jpg', 3, 1),
		('minecraft', 'If you like the cube, this torch is for you',3, 'https://vendugeek.com/3461-large_default/lampe-torche-minecraft.jpg', 3, 1),
		('rake', 'an implement consisting of a pole with a toothed crossbar or fine tines at the end, used especially for cook sausage',2 ,'https://idata.over-blog.com/1/40/89/72//bbq-rateau-gazon.jpg', 4, 1),
		('caddy supermarket', 'it is just a caddy', 1, 'https://lh3.googleusercontent.com/proxy/0Q19lgEdfkbySVg5JRENoDCxik_aSST03kPgxNaBc-IdTERzv0zzMNDm05ghnvchtA8sdbvB21oKZEbjqAOGDua3LMqGbILdZBzSWjs1Ug', 4, 1),
		('concrete block', 'made in Portugal CARAI', 1, 'https://www.batidrive-balan.com/53-home_default/parpaing-creux-15x20x50.jpg', 4, 1),
		('Thor', 'It is Asgard''s most powerful weapon and the symbol of the mighty God of Thor, able to defeat Giants and unleash lightning.', 20, 'http://scotdir.com/wp-content/uploads/2015/12/norse-mythology-thor-hammer-of-the-gods_1.jpg', 5, 1),
		('gavel', 'To judge your friends', 5, 'https://www.laboutiqueinsolite.com/928-thickbox_default/marteau-d-encheres-maillet-juge.jpg', 5, 1),
		('Splutter', 'Droplet of saliva projected while speaking: Send postilions.', 10, 'https://www.manutan.fr/img/S/GRP/ST/AIG1893301.jpg', 5, 1),
		('hammerhead shark', 'The common hammerhead shark is easily distinguished from other shark species by the compressed head that characterizes it. Its skull, large and flattened, gives it a unique shape.', 40, 'https://lh4.googleusercontent.com/_1bP-bEN6YF0fPjEa0QR6erzfUZJoeDgKSqTTHq-iohbyzC8mO4N25ZN7ecyO_OZvTH21J_Qn5PQx78iUKco222d7FBFC0AL1C_pk3Ls6wwJiddoloNPiQgKmtVeuQu6LiJY00c', 5, 1),
		('Mikado', 'thiner but longer', 5, 'https://media3.petitzebre.com/101651-thickbox_default/mikado-geant.jpg', 6, 1),
		('Oak', 'Strong like an oak!', 3, 'https://balla-cosmetiques.com/661-large_default/siwa-baton-dentaire-x3.jpg', 6, 1),
		('Birch', 'Do you have a birch tree nearby? Good now you also have a birch stick', 4, 'https://scx2.b-cdn.net/gfx/news/2017/3-theevolution.jpg', 6, 1),
		('Cottonwood', 'Smooth cottonwood for a smoother hit', 5, 'https://cf.ltkcdn.net/garden/images/orig/204351-2125x1411-Cottonwood-Tree-in-Autumn.jpg', 6, 1),
		('Vibrating', 'When you need to make your enemies shake in fear but also physically', 49, 'https://images-na.ssl-images-amazon.com/images/I/51AHZGMp01L._AC_SX679_.jpg ', 7, 3),
        ('Oak', 'A thicker stronger Oak stick, nevermind the shorter size', 23, 'https://jardinage.lemonde.fr/images/dossiers/historique/mini/chenes-171748-650-325.jpg', 7, 3),
        ('Birch', 'A thicker Birch stick, serves all hitting purposes', 20, 'https://www.jardinet.fr/blog/wp-content/uploads/2017/11/Tout-savoir-sur-le-bouleau.jpg', 7, 3),
        ('Basic', 'The basic spear you will need in your life', 10,'https://inserezunepiece.files.wordpress.com/2016/05/carrot-on-a-stick.jpg?w=584', 8, 3),
        ('For Mammoths', 'The one you must have to hunt some big mammals.',  15, 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Neptune_cruise_missile_05.jpg', 8, 3),
        ('For Beavers', 'Thin and and lightweight perfect to hunt small animals.', 14, 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Neptune_cruise_missile_05.jpg', 8, 3),
        ('For People', 'Sharpest then a shark is theet the perfect tool to kill you friend.', 100, 'https://static.turbosquid.com/Preview/2014/10/01__13_59_52/render1.pngd653606e-2afd-45df-8653-6b1b2aeafee2Large.jpg', 8, 3),
        ('Useless', 'Just a spear.', 10, 'https://image.shutterstock.com/image-photo/pointed-stick-sharp-wooden-spear-260nw-1631071417.jpg', 8, 3),
        ('Mammoth ligament', 'Made of a ligament of mammouth', 4, 'http://www.survie-et-survivalisme.com/wp-content/uploads/2016/10/lance-pierre-en-bois.jpg', 9, 3),
        ('Fémur bone', 'Made of human femure.', 8, 'https://www.chefcook.fr/4707-intermediaire_default/os-de-veau-femur-scie.jpg', 9, 3),
        ('Classic', 'The basic sling.', 20, 'https://i.pinimg.com/564x/c1/5e/0f/c15e0fef4edcfe838d5255a40e90ca42.jpg', 9, 3),
        ('Compound bow', 'Bow with a pulley to increase its range.', 12, 'https://www.erhart-sports.com/4536-thickbox_default/hoyt-alpha-rx4-arc-a-poulies-de-chasse.jpg', 10, 3),
        ('Longbow', 'Long bow to hunt from long distance.', 19, 'https://la-forge-medievale.com/927-large_default/-arc-long-viking-70-.jpg', 9, 3),
        ('Shortbow', 'Small and robust you can take it everywhere.', 18, 'https://tangrammontessori.com/8922-large/petit-arc.jpg', 10, 3),
        ('x20', 'A stack of arrow.', 25, 'https://m.media-amazon.com/images/I/51oZfRK2K+L._AC_SY450_.jpg', 11, 3),
        ('Prehistoric tobacco', 'Tobacco to dry', 8, 'https://i1.wp.com/lesmoutonsenrages.fr/wp-content/uploads/2014/12/tobacco-19997_640.jpg', 12, 4),
        ('Weed do-it yourself', 'The weed you would never have given to your mom', 150, 'https://cdn.aarp.net/content/dam/aarp/health/drugs_supplements/2019/08/1140-med-marijuana-caduceus.imgcache.rev873985b7234d2a2df9a09f5cefacea57.jpg', 12, 4),
        ('Smoking bear skin', 'first catch a bear and then think of smoking', 1000, 'https://lh3.googleusercontent.com/proxy/vViBhqCJzfGuAADRn-3kM0jywGO_1TV2dWL9JcfG448pTdReH8Yx1bzg8ye5zD7ev-lvXDCohZo0RcEaw39vr0L8uSHGUrZwmtmVKJ8', 12, 4),
        ('Smoking yak hair', 'then catch a yak and a barber at the same time', 900, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg/1200px-Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg', 12, 4),
        ('Paleo apero', 'Apero time', 20, 'https://www.lanutrition.fr/sites/default/files/styles/preview_article_medium_line/public/ressources/aliments_diabete_glucometres.jpg?itok=Mo9HWzNX', 13, 4),
        ('Grapes', 'Learn to cultivate grape and forget about juices!', 8, 'https://www.irbms.com/wp-content/uploads/2019/09/raisin-sante-600x400.jpg', 14, 5),
        ('Press', 'it is time to get your feet dirty ', 12, 'https://www.champagne.fr/assets/images/3-vigne-au-vin/Elaboration/pressoir-traditionnel.jpg', 14, 5),
        ('Barrel', 'you cannot wait for the iron to be invented!', 52, 'https://www.temesso.fr/media/image/67/7b/ff/tonneau-de-decoration-table-bar-225-litres-en-bois-de-che-ne-massif-1.jpg', 14, 5),
        ('Hop', 'it will become your favourite drink even before water', 20, 'https://www.challenges.fr/assets/afp/2020/04/25/f63aca8f6a95d7bd10b3a2e6dee2580a28787d2a.jpg', 15, 5),
        ('Malt', 'you need to buy hop first', 15, 'https://njmonthly.com/wp-content/uploads/cache/2017/07/malt/1133944283.jpg', 15, 5),
        ('Yeast', 'if you have found the 2 previous articles of Beers section, then cath this one', 3, 'https://cdn.bioalaune.com/img/article/thumb/900x500/13757-levure_de_biere_complement_alimentaire_naturel_aux_multiples_bienfaits.jpg', 15, 5);


	    